FROM jenkins/jenkins:lts

USER root

# Docker Compose (ARM64 uyumlu – senin makineye göre)
RUN curl -L https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-aarch64 \
    -o /usr/local/bin/docker-compose \
 && chmod +x /usr/local/bin/docker-compose

USER jenkins
