version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-blueocean
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet

  app:
    build: .
    container_name: techlogist_app
    networks:
      - testnet

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    networks:
      - testnet

networks:
  testnet:
    name: techlogist_testnet

volumes:
  jenkins_home: